#!/bin/bash
# run rclone sync to backup user files.
# currently lives in $HOME/.local/bin
# usage: $ rcs -ug
#
# opts:
#   -g
#       go: run rclone sync without --dry-run flag
#   -d
#       download changes from remote, rather than
#       upload changes
#   -u
#       upload changes from local to remote,
#       rather than download
#   -t
#       targets: specify a single folder name in ~/docs,
#       or write 'all' to sync all folders. required flag.

# define logfile
log_file=~/synclog.txt

# dry_run should be true by default!
# i.e., don't make changes but see what would happen.
# change with -g argument (for 'go').
dry_run=true

# get options
# t: means we require the -t tag, with parameters
targets=false
while getopts ":dugt:" opt; do
    case $opt in
        d) download=true                          ;;
        u) upload=true                            ;;
        g) dry_run=false                          ;;
        t) targets=${OPTARG}               ;;
        \?) echo "Invalid option: -$OPTARG" >&2   ;;
    esac
done

# check that targets have been supplied
if [ ! $targets ] ; then
    echo "-t with an argument must be specified."
    exit 1
fi

# decide whether to sync all folders or just a selected folder
if [ "$targets" == "all" ] ; then
    echo "Syncing all folders!"
    target_dirs=('code' 'financial' 'personal' 'media')
else
    echo "Syncing $targets folder only!"
    target_dirs=$targets
fi



# don't allow -u and -d at the same time!
if [ "$download" = true ] && [ "$upload" = true ] ; then
    echo "You can only supply one of -u and -d."
    exit 1
fi

# define source and remote destinations
if [ "$download" = true ] ; then
    echo Downloading files...
    source_dir=remote-crypt:
    dest_dir=~/docs/
elif [ "$upload" = true ] ; then
    echo Uploading files...
    source_dir=~/docs/
    dest_dir=remote-crypt:
else
    echo "Please supply a -u or -d flag."
    exit 1
fi

for folder in "${target_dirs[@]}"
    do
        sync_status="Syncing $folder folder"
        if [ "$dry_run" = true ] ; then
            sync_status="$sync_status as a dry run"
            echo $sync_status
            rclone sync $source_dir$folder $dest_dir$folder \
                --dry-run \
                -v \
                --drive-chunk-size 512M \
                --transfers=20 \
                --fast-list \
                2>&1 | tee -a ${log_file}
        else
            echo $sync_status
            rclone sync $source_dir$folder $dest_dir$folder \
                -v \
                --drive-chunk-size 512M \
                --transfers=20 \
                --fast-list 2>&1 | tee -a ${log_file}
        fi
    done

# note some flags can speed up the upload process
# which has been fucking slow for me recently
# e.g.
# rclone sync source remote -P --drive-chunk-size 512M --max-backlog 999999
# --transfers=75 --fast-list

# i believe --check-first is basically the same as --max-backlog 999999

# transfers seemed to increase from default, 20, 40, 60 - then
# decrease speed at 100. So went with 75, might not be optimal.
# --drive-chunk-size decreased at 1024 cf 512.
